[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "linked_census"
description = "titanic_ml example package"
version = "0.5.0"
authors = [{name = "Andrea Musso"}]
requires-python = ">=3.7"
dependencies = ["pandas >= 2.0.0"]